[REQUEST]: Add information for installing TgCli with Guix.
erayerdin/tgcli pull request #49
Opened 2021-05-31 22:54 UTC by raghavgururajan

I recently [packaged](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=49d8f954e631abaec08fc58f58cbfd13c3aabc41) TgCli into Guix.

Could you please add information for installing TgCli with Guix, in README file?

2021-06-01 04:55 UTC, erayerdin requested changes
Thank you for contribution. There's a *slight* thing. I refer to the project as "tgcli" in many places, not "TgCli".

2021-06-01 04:55 UTC, erayerdin commented on README.md
> +TgCli is [available](https://guix.gnu.org/en/packages/tgcli-0.3.1/) in official channel of Guix.
Just a slight thing. I think it should be "tgcli", not "TgCli".

2021-06-01 04:55 UTC, erayerdin commented on README.md
> +TgCli is [available](https://guix.gnu.org/en/packages/tgcli-0.3.1/) in official channel of Guix.
```suggestion
tgcli is [available](https://guix.gnu.org/en/packages/tgcli-0.3.1/) in official channel of Guix.
```

2021-06-01 05:12 UTC, erayerdin commented
Ok, seems like I can also change it. I fixed the typo and will merge asap.

2021-06-01 05:18 UTC, merged

2021-06-04 04:04 UTC, raghavgururajan commented
@erayerdin 

Thanks for the merge. :)